using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UIPanelGame : MonoBehaviour,IMenu
{

    [SerializeField] private Button btnPause;
    

    private UIMainManager m_mngr;

    private void Awake()
    {
        btnPause.onClick.AddListener(OnClickPause);
    }
    
    private void OnDestroy()
    {
        if (btnPause) btnPause.onClick.RemoveAllListeners();
    }

    private void OnClickPause()
    {
        m_mngr.ShowPauseMenu();
    }
    

    public void Setup(UIMainManager mngr)
    {
        m_mngr = mngr;
    }

    public void Show()
    {
        this.gameObject.SetActive(true);
    }

    public void Hide()
    {
        this.gameObject.SetActive(false);
    }
}